format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$docker_context\
$cmd_duration\
$fill
> 
"""
right_format = """
$python\
$nix_shell\
$kubernetes
"""
[fill]
symbol = ''

[python]
style = "dimmed white"
format = '[ $virtualenv]($style)'

[kubernetes]
disabled = false
style = "dimmed orange"
format = '[ $symbol $context]($style)'

[nix_shell]
style = "dimmed blue"
format = ' [$name]($style)  '

[username]
show_always = true
style_user = 'dimmed white'
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
disabled = true # Disabled by default

[directory]
style = "dimmed white"
format = "[$path]($style)"
truncation_length = 2
truncation_symbol = "..."

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Code" = "🐙"
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "


[docker_context]
symbol = " "
format = '[ $symbol $context ]($style)'


[git_branch]
symbol = ""
format = '[ $symbol $branch ]($style)'

[git_status]
style = "dimmed white"
format = '[$all_status$ahead_behind ]($style)'
ahead = '✈️'
modified = "💩"
up_to_date = "🌈"
stashed = ""

[golang]
symbol = " "
format = '[ $symbol ($version) ]($style)'


[nodejs]
symbol = ""
format = '[ $symbol ($version) ]($style)'


[rust]
symbol = ""
format = '[ $symbol ($version) ]($style)'


[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'

[cmd_duration]
disabled = false
format = '[$duration]($style)'
